// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Rule struct {
	Rule  string `json:"rule"`
	Value int    `json:"value"`
}

type Verify struct {
	Verify  bool      `json:"verify"`
	NoMatch []*string `json:"noMatch"`
}
